### ISSUE TITLE
deleteFromObjectByKey(object, key)

### ISSUE THREAD

**Issue by vktrwlt** [learn-co-curriculum/javascript-objects-lab#3]
The tester doesn't check if you deleted the key destructively or not.

I passed the test with 

delete object[key];
return object;

**Comment by aturkewi** [comment]
This issue was also raised here on the wrong lab: https://github.com/learn-co-curriculum/javascript-objects/issues/11#issuecomment-267404904 See that issue for more detailed notes.

**Comment by aturkewi** [comment]
@victorwltsang I just tested this and a test seems to fail with that code:
```javascript
function deleteFromObjectByKey(object, key) {
  // const newObj = Object.assign({}, object)

  delete object[key]

  return object
}
``` 
yields:
```
// ♥ learn

> javascript-objects-lab@0.1.0 test /Users/avidor/Development/code/instructor/fix_labs/javascript-objects-lab
> mocha -R mocha-multi --reporter-options nyan=-,json=.results.json

 4   -_-_-__,------,
 1   -_-_-__|  /\_/\ 
 0   -_-_-_~|_( x .x) 
     -_-_-_ ""  "" 

  4 passing (998ms)
  1 failing

  1) Objects deleteFromObjectByKey(object, key) deletes `key` from a clone of object and returns the new object (it is non-destructive):
     Error: Expected {} to match { prop: 1 }
      at assert (node_modules/expect/lib/assert.js:29:9)
      at Expectation.toMatch (node_modules/expect/lib/Expectation.js:138:28)
      at Context.<anonymous> (test/index-test.js:42:19)



npm ERR! Test failed.  See above for more details.
```

It's possible that this test has been updated since then though. In any case, it seems to be working now!
