### ISSUE TITLE
updateObjectWithKeyAndValue issue

### ISSUE THREAD

**Issue by aturkewi** [learn-co-curriculum/javascript-objects-lab#7]
Copying issues over from https://github.com/learn-co-curriculum/javascript-objects/issues/11#issuecomment-267404904

Same answer for destructivelyUpdateObjectWithKeyAndValue works with updateObjectWithKeyAndValue

Both of these pass the test.

```javascript
function updateObjectWithKeyAndValue(object, key, value){
  return Object.assign ({}, object, {[key] : value})
}
```

```javascript
function updateObjectWithKeyAndValue(object, key, value){
  object[key]=value
  return object
}
```

Originally posted by @latinadeveloper

**Comment by aturkewi** [comment]
I'm not seeing the same results. When I set the function to:

```javascript
function updateObjectWithKeyAndValue(object, key, value) {
  // return Object.assign({}, object, { [key]: value })
  delete object[key]

  return object
}
```

I get the following errors:
```
// ♥ learn

> javascript-objects-lab@0.1.0 test /Users/avidor/Development/code/instructor/fix_labs/javascript-objects-lab
> mocha -R mocha-multi --reporter-options nyan=-,json=.results.json

 3   -_-_-__,------,
 2   -_-_-__|  /\_/\ 
 0   -_-_-_~|_( x .x) 
     -_-_-_ ""  "" 

  3 passing (989ms)
  2 failing

  1) Objects updateObjectWithKeyAndValue(object, key, value) returns a clone of `object` by adding `key` and `value` (it is non-destructive):
     Error: Expected { prop: 1 } to match { prop: 1, prop2: 2 }
      at assert (node_modules/expect/lib/assert.js:29:9)
      at Expectation.toMatch (node_modules/expect/lib/Expectation.js:138:28)
      at Context.<anonymous> (test/index-test.js:12:60)

  2) Objects deleteFromObjectByKey(object, key) deletes `key` from a clone of object and returns the new object (it is non-destructive):
     Error: Expected {} to match { prop: 1 }
      at assert (node_modules/expect/lib/assert.js:29:9)
      at Expectation.toMatch (node_modules/expect/lib/Expectation.js:138:28)
      at Context.<anonymous> (test/index-test.js:42:19)



npm ERR! Test failed.  See above for more details.
```

It's possible that this test has been update since the issue was raised, but it looks like it's all set now!
